template: true
valuesFilePath: ./values.yml

resources:
- name: {{.Values.pipeline.name}}_GitRepo
  type: GitRepo
  configuration:
    gitProvider: {{.Values.repo.gitProvider}}
    path: {{.Values.repo.path}}
    branches:
      include: ^master$
    buildOn:
      commit: true
    cancelPendingRunsOn:
      newCommit: true

pipelines:
- name: {{.Values.pipeline.name}}
  configuration:
    jfrogCliVersion: 2
    environmentVariables:
      readOnly:
        JFROG_CLI_PLUGINS_SERVER: {{.Values.artifactory}}
        JFROG_CLI_BUILD_NUMBER: ${run_id}
        JFROG_CLI_LOG_LEVEL: DEBUG
    runtime:
      type: image
      image:
        custom:
          name: {{.Values.languages.go.image}}
          tag: '{{.Values.languages.go.version}}'
  steps:
  - name: build
    type: Bash
    configuration:
      integrations:
      - name: {{.Values.artifactory}}
      - name: {{.Values.jira}}
      inputResources:
      - name: {{.Values.pipeline.name}}_GitRepo
    execution:
      onExecute:
      - pushd $(find_resource_variable "{{.Values.pipeline.name}}_GitRepo" resourcePath)

      - go build -o ext-build-info

      - ./ext-build-info collect-issues --tracker=Jira ${pipeline_name} ${run_number}
      - popd
