resources:
- name: ExtBuildInfo_GitRepo
  type: GitRepo
  configuration:
    gitProvider: Github
    path: marvelution/ext-build-info
    branches:
      include: ^master$
    buildOn:
      commit: true
    cancelPendingRunsOn:
      newCommit: true

pipelines:
- name: ExtBuildInfo
  configuration:
    jfrogCliVersion: 2
    environmentVariables:
      readOnly:
        JFROG_CLI_PLUGINS_SERVER: Artifactory
    runtime:
      type: image
      image:
        auto:
          language: go
          versions:
          - "1.19"
  steps:
  - name: build
    type: Bash
    configuration:
      integrations:
      - name: Artifactory
      - name: Jira
      inputResources:
      - name: ExtBuildInfo_GitRepo
    execution:
      onExecute:
      - pushd $(find_resource_variable "ExtBuildInfo_GitRepo" resourcePath)

      - go build -o ext-build-info
      - export version=$(./ext-build-info --version | awk '{print $3}')

      - ./ext-build-info collect-issues --tracker=Jira ${pipeline_name} ${run_number}

      - jf plugin publish ext-build-info "$version"
      - popd
